# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 06:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alamat',
            fields=[
                ('id_alamat', models.CharField(db_column='ID_ALAMAT', max_length=6, primary_key=True, serialize=False)),
                ('alamat', models.CharField(db_column='ALAMAT', max_length=25)),
                ('kode_pos', models.CharField(db_column='KODE_POS', max_length=5)),
            ],
            options={
                'db_table': 'alamat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('kode_barang', models.CharField(db_column='KODE_BARANG', max_length=5, primary_key=True, serialize=False)),
                ('nama_barang', models.CharField(db_column='NAMA_BARANG', max_length=15)),
                ('deskripsi_barang_field', models.TextField(db_column='DESKRIPSI_BARANG_')),
                ('harga_barang', models.FloatField(db_column='HARGA_BARANG')),
                ('tanggal_datang', models.DateTimeField(db_column='TANGGAL_DATANG')),
            ],
            options={
                'db_table': 'barang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('waktu_pemesanan', models.DateTimeField(db_column='WAKTU_PEMESANAN', primary_key=True, serialize=False)),
                ('kuantitas_barang', models.SmallIntegerField(blank=True, db_column='KUANTITAS_BARANG', null=True)),
            ],
            options={
                'db_table': 'cart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('email', models.CharField(db_column='EMAIL', max_length=20, primary_key=True, serialize=False)),
                ('nama_customer', models.CharField(db_column='NAMA_CUSTOMER', max_length=30)),
                ('telp_customer', models.SmallIntegerField(db_column='TELP_CUSTOMER')),
                ('password', models.CharField(db_column='PASSWORD', max_length=15)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kota',
            fields=[
                ('id_kota', models.CharField(db_column='ID_KOTA', max_length=5, primary_key=True, serialize=False)),
                ('nama_kota', models.CharField(db_column='NAMA_KOTA', max_length=30)),
            ],
            options={
                'db_table': 'kota',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Provinsi',
            fields=[
                ('id_provinsi', models.CharField(db_column='ID_PROVINSI', max_length=2, primary_key=True, serialize=False)),
                ('nama_provinsi', models.CharField(db_column='NAMA_PROVINSI', max_length=25)),
            ],
            options={
                'db_table': 'provinsi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Simpanwishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'simpanwishlist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipeBarang',
            fields=[
                ('kode_tipe', models.CharField(db_column='KODE_TIPE', max_length=5, primary_key=True, serialize=False)),
                ('tipe_barang', models.CharField(db_column='TIPE_BARANG', max_length=6)),
            ],
            options={
                'db_table': 'tipe_barang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('foto_bukti', models.TextField(db_column='FOTO_BUKTI')),
                ('waktu_bayar', models.DateTimeField(db_column='WAKTU_BAYAR')),
                ('bank_tujuan', models.CharField(db_column='BANK_TUJUAN', max_length=10)),
                ('rek_pengirim', models.CharField(db_column='REK_PENGIRIM', max_length=12)),
                ('kode_transaksi', models.CharField(db_column='KODE_TRANSAKSI', max_length=10, primary_key=True, serialize=False)),
                ('status_konfirmasi', models.IntegerField(db_column='STATUS_KONFIRMASI')),
                ('total_harga', models.FloatField(db_column='TOTAL_HARGA')),
            ],
            options={
                'db_table': 'transaksi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetailBarang',
            fields=[
                ('kode_barang', models.ForeignKey(db_column='KODE_BARANG', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='apiolshop.Barang')),
                ('ukuran', models.CharField(db_column='UKURAN', max_length=5)),
                ('warna', models.CharField(db_column='WARNA', max_length=50)),
                ('bahan', models.CharField(db_column='BAHAN', max_length=20)),
                ('foto_barang', models.TextField(db_column='FOTO_BARANG')),
                ('stock', models.SmallIntegerField(blank=True, db_column='STOCK', null=True)),
            ],
            options={
                'db_table': 'detail_barang',
                'managed': False,
            },
        ),
    ]
