# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiolshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarangPesanan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_barang_pesanan', models.CharField(db_column='ID_BARANG_PESANAN', max_length=2)),
            ],
            options={
                'managed': False,
                'db_table': 'barang_pesanan',
            },
        ),
        migrations.CreateModel(
            name='DaftarAlamat',
            fields=[
                ('id_alamat', models.CharField(db_column='ID_ALAMAT', max_length=6, primary_key=True, serialize=False)),
                ('alamat', models.CharField(db_column='ALAMAT', max_length=25)),
                ('kode_pos', models.CharField(db_column='KODE_POS', max_length=5)),
            ],
            options={
                'managed': False,
                'db_table': 'daftar_alamat',
            },
        ),
    ]
